dist: bionic
sudo: required

language: node_js
node_js:
  - '12'

os:
  - linux

cache:
  directories:
    - ./node_modules

before_script:
  - sh -e /etc/init.d/xvfb start
  - npm install -g @angular/cli

install:
  - npm install

script:
  - npm run lint
  - npm run lint:js
  - npm run prettier:check
  - npm run build:prod
  - npm run test:ci
  - npm run e2e:ci
